language: generic
sudo: required
services:
  - docker

script:
  - docker run -v $PWD:/liquid-swap debian:stretch@sha256:724b0fbbda7fda6372ffed586670573c59e07a48c86d606bab05db118abe0ef5 /bin/bash -c "cd /liquid-swap && ./tools/test.sh"
